### PR TITLE
[FIXED] ErrorHandler not always reporting proper error

### LINKED ISSUE #325: ErrorHandler not always reporting proper error
Say that your application has no permission to publish and subscribe on foo.
```
nc.subscribe('foo', cb)
nc.publish('foo', []byte("hello")
```
These 2 calls should result in getting permission violation errors presented
to the ErrorHandler, one for the subscribe, one for the publish.
However, the error handler will be invoked with 2 errors corresponding
to the publish permission error. If the application was doing a publish
then a subscribe, the error callback will likely get 2 errors about permission
violation related to subscription.

### PR DESCRIPTION
**Pull request by kozlovic**
The issue was that we were using `nc.err` as a parameter of
the closure function sent to `nc.ach`. The value of the error
would then change and be whatever last value is.
We now create an error so that this is unique per scheduled
async error.

Updated the test that checks not only that we get the permission
violation error, but that we get the expected one (one for sub
and for for pub).

Resolves #325

### CODE REVIEW

File: nats.go [hunk 1]
```diff
@@ -1682,9 +1682,11 @@ slowConsumer:
 // permissions violation on either publish or subscribe.
 func (nc *Conn) processPermissionsViolation(err string) {
 	nc.mu.Lock()
-	nc.err = errors.New("nats: " + err)
+	// create error here so we can pass it as a closure to the async cb dispatcher.
+	e := errors.New("nats: " + err)
```
Comment (tylertreat) [inline nats.go]: Unrelated to this, but IMO we should consider using "typed" errors. Users should not have to resort to parsing error strings to handle different errors.
